version: '3.9'

services:
  add_service:
    container_name: add_service
    image: z4nd3rx/spring_services:add_service_v1.0.0
    build: ./add
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
  put_service:
    container_name: put_service
    image: z4nd3rx/spring_services:put_service_v1.0.0
    build: ./put
    ports:
      - 8082:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
  get_service:
    container_name: get_service
    image: z4nd3rx/spring_services:get_service_v1.0.0
    build: ./get
    ports:
      - 8083:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
  delete_service:
    container_name: delete_service
    image: z4nd3rx/spring_services:delete_service_v1.0.0
    build: ./delete
    ports:
      - 8084:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /home/z4nd3rx/EAM_CNC/parcial2/docker/postgres_data:/var/lib/postgresql/data